//
//  hydrationView.swift
//  clarityProject
//
//  Created by Scholar on 7/18/23.
//

import SwiftUI

struct hydrationView: View {
    
    @State var selectionIndex: Int = 1
    
    var body: some View {
        ZStack {
            Image("beginnerMain")
                .aspectRatio(contentMode: .fill)
                .padding(.leading, 40.0)
                
            VStack {
               Text("Hydration Tracker")
                     .font(.largeTitle)
                     .fontWeight(.bold)
                     .foregroundColor(Color.black)
                 .padding([.leading, .bottom, .trailing], 50.0)
        
                Text ("Hydration is one of the most important things in order to maintain a happy and healthy body. Staying hydrated can: increase energy levels; prevent headaches; maximize physical performance and improve brain functions. The minimum amount of water we should drink is about 8 cups (64 oz) a day.")
                    .font(.title2)
                    .fontWeight(.semibold)
                 .foregroundColor(Color.black)
                 .multilineTextAlignment(.center)
                 .padding([.leading, .bottom, .trailing], 50.0)
                 .frame(width: 400.0)
                
               Picker(selection: $selectionIndex, label: Text("Picker"), content: {
                 Text("1").tag(1)
                 Text("2").tag(2)
                 Text("3").tag(3)
                 Text("4").tag(4)
                 Text("5").tag(5)
                 Text("6").tag(6)
                 Text("7").tag(7)
                 Text("8").tag(8)
                 Text("9").tag(9)
                 Text("10").tag(10)
                   
               })
               .accentColor(.black)
               .background()
               .cornerRadius(20.0)
                 
               HStack {
                 if (selectionIndex == 1){
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                 } else if (selectionIndex == 2) {
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                 } else if (selectionIndex == 3) {
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                 } else if (selectionIndex == 4) {
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                 } else if (selectionIndex == 5) {
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                 } else if (selectionIndex == 6) {
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 50)
                 } else if (selectionIndex == 7) {
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                 } else if (selectionIndex == 8){
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                   Image("cupOfWater")
                     .resizable()
                     .aspectRatio(contentMode: .fit)
                     .frame(width: 40)
                 } else if (selectionIndex == 9){
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 35)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 35)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 35)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 35)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 35)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 35)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 35)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 35)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 35)
                           } else {
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 30)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 30)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 30)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 30)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 30)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 30)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 30)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 30)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 30)
                             Image("cupOfWater")
                               .resizable()
                               .aspectRatio(contentMode: .fit)
                               .frame(width: 30)
                           }
                         }
                         }
                       }
                      }
                   }
                    struct hydrationView_Previews: PreviewProvider {
                       static var previews: some View {
                         hydrationView()
                       }
                     }
        
  
